package model.mapobjects.features;

/*need to press stones in right order to open (generated by random each time)*/
public class FourStoneGate extends Gate {

    public FourStoneGate(int y, int x, int yblock, int xblock) {
        super(y, x, yblock, xblock);
        examineDescription = "A solid stone gateway with a flat cylinder also made of stone set into the doors."
            + "the cylinder is separated into 4 equal pieces by a cross shaped cut.";
    }

    /*requires:
    * modifies: this
    * effects: if player enters directions in the correct order, open the gate
    * password is up down left down*/
    @Override
    public boolean examine(String ui) {
        return false;
    } //todo
}
