package model.mapobjects.features;

/*need to press stones in right order to open (generated by random each time)*/
public class FourStoneGate extends Gate {
//todo where is pw hidden???

    public FourStoneGate(int y, int x, int yblock, int xblock) {
        super(y, x, yblock, xblock);
        examineDescription = "Inscribed in the stone at the foot of the gate is "
                + "the words 'everything is in the way it moves'";
    }

    /*requires:
    * modifies: this
    * effects: if player enters directions in the correct order, open the gate
    * password is updown left down*/
    @Override
    public boolean examine(String ui) {
        return false;
    }
}
